twig:
    file_name_pattern: '*.twig'
    form_themes: ["bootstrap_5_layout.html.twig"]
    globals:
        categoryRepository: '@App\Repository\CategoryRepository'
        cartService: '@App\Cart\CartService'

when@test:
    twig:
        strict_variables: true
